// mf_contenedor/src/App.tsx
import React from "react";
import {createRoot} from "react-dom/client";

import "./index.css";

import "PersonalDashboard/index"
import { Dasboard } from "PersonalDashboard/components/pages/Dasboard";

import "svelte/index"
import Home from "svelte/Home";

const App = () => (
  <div className="container">
    <div>Name: mf_contenedor</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
    <Home/>
    <Dasboard/>
  </div>
);

const root = createRoot(document.getElementById("app") !);
root.render(<App/>);

//ReactDOM.render(<App />, document.getElementById("app"));

// bb-mf-template/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";

import "./index.css";

const App = () => (
  <div className="container">
    <div>Name: bb-mf-template</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Empty CSS</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById("app"));
